### ISSUE TITLE
Add base config to allow users to specify files other than just .js files

### ISSUE THREAD

**Issue by C5m7b4** [C5m7b4/symmetra#2]
**Is your feature request related to a problem? Please describe.**
It would be nice if the user could specify files other than .js files for the initial scrub of the project folder.

**Describe the solution you'd like**
Add an additional configuration for baseFileExtension (.txt or other). Then add to the parameters of the Watcher function with default value of 'js'

**Comment by MikeBedingfield** [comment]
I would like to work on this if nobody is tackling it yet.
